### ISSUE TITLE
In SF 3.2.6, problem to generate i18n routes in production mode.

### ISSUE THREAD

**Issue by Crusider** [BeSimple/BeSimpleI18nRoutingBundle#102]
Hello,

My project is in SF 3.2.6 and I try to generate the i18n routes in production mode.

In dev mode, it's ok.

But in production mode, routes generated are always in same locale (the current).

I use this link to switch : 
```
<a href="{{ path(app.request.attributes.get('_route'), {'locale': 'fr'}) }}">fr</a>
<a href="{{ path(app.request.attributes.get('_route'), {'locale': 'en'}) }}">en</a>
```

Can you help me ?

Thank you in advance.

**Comment by Crusider** [comment]
I found the solution.

For work in the dev mode, I had to update the "_main" route in "routing_dev.yml" with "type: be_simple_i18n" like this :
```
_main:
    resource: routing.yml
    type: be_simple_i18n
```

And the solution for the production mode is to add the same line in the "config.yml" where the "routing.yml" is imported like this :
```
framework:
    ...
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        type: be_simple_i18n
```
