### ISSUE TITLE
Annotation routing I18l is not working for Symfony 3.4

### ISSUE THREAD

**Issue by kusiu** [BeSimple/BeSimpleI18nRoutingBundle#112]
[I18nRoutingBundle][1] doesn't seem to be working for Symfony 3.4.

**JobController.php**

  
    use BeSimple\I18nRoutingBundle\Routing\Annotation\I18nRoute;

    class JobController extends Controller
    {
        /**
         *
         * @I18nRoute({ "en": "/jobs", "pl": "/ogloszenia" }, name="jobs")
         * @Method("GET")
         */
        public function jobsListAction()
        {
            $jobs = $this->getDoctrine()
                ->getRepository(Job::class)
                ->findAllActive();
        
            return $this->render('job/list.html.twig', [
                'jobs' => $jobs,
            ]);
        }
    }

**config.yml**

    be_simple_i18n_routing:
        annotations: true

**error:**

    An exception has been thrown during the rendering of a template ("I18nRoute "jobs" (pl) does not exist.").

  [1]: https://github.com/BeSimple/BeSimpleI18nRoutingBundle

**Comment by borjanavarro** [comment]
Same here

**Comment by kusiu** [comment]
Does anyone have this problem too?

**Comment by kusiu** [comment]
Ok, to fix the problem `new BeSimple\I18nRoutingBundle\BeSimpleI18nRoutingBundle()` needs to be placed at the beginning of bundles list in `AppKernel.php`

Its actually half fixed. I realised that standard annotation`@Route()` doesn't work.

Anyone?

**Comment by Sentence** [comment]
It works for me on multiple project with these, like yours:
(But i forked this project to update some things :))

config.yml
```yaml
parameters:
    locales: [hu, en, de] # change them to [en, pl]

# ...

be_simple_i18n_routing:
    annotations: true
```

controlelr:
```php
use BeSimple\I18nRoutingBundle\Routing\Annotation\I18nRoute;

class DefaultController extends Controller
{
    /**
     * @I18nRoute({"hu": "/fooldal/", "en": "/homepage/", "de": "/startseite/"}, name="homepage")
     */
    public function indexAction(Request $request)
    {
        // ...
```

---

Use method restrictions in route declaration, like this:
```@I18nRoute({ "en": "/jobs", "pl": "/ogloszenia" }, name="jobs", methods={"GET"})```

---

So probably you missed the locales in parameter section, but you can try add these line to `config.yml`:
```yml
parameters:
    locale: en

framework:
    translator: { fallbacks: ['%locale%'] }
```

Or try in `routing.yml`:
```yaml
app:
    resource: '@AppBundle/Controller/'
    type: annotation
```
