### ISSUE TITLE
How to pass BeSimpleI18nRouting as a service argument?

### ISSUE THREAD

**Issue by WojciechJasinski** [BeSimple/BeSimpleI18nRoutingBundle#35]
Hi,
I've had to write AuthenticationSuccesshandler in my project and I need to get access to routing from within this service.
This is how this handler is defined:

```
services:
    authentication_handler:
        class: Strict\UserBundle\Handler\AuthenticationHandler
        arguments: [____BeSimpleI18nRouting HERE_____]
        calls:
            - [ setContainer, [ @service_container ] ] 
```

What I need to do is to pass BeSimpleI18nRouting to my handler constructor as an argument.
Any ideas how I can do this?
