### ISSUE TITLE
FileLoaderLoadException: Cannot import resource 

### ISSUE THREAD

**Issue by Worstkaes** [BeSimple/BeSimpleI18nRoutingBundle#63]
Hey,

I'm trying to get work with i18n Routingbundle, but I get the following error: 

**FileLoaderLoadException: Cannot import resource**
'The routing file … contains unsupported keys for "welcome": "locales". Expected one of: "resource", "type", "prefix", "pattern", "path", "host", "schemes", "methods", "defaults", "requirements", "options", "condition".'

**My config.yml looks like:**

```
be_simple_i18n_routing: ~
framework:
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        type: be_simple_i18n
```

**And my routing.yml looks like:**

```
welcome:
    locales:  { de: "/willkommen", en: "/welcome" }
    defaults: { _controller: MyBundle:Welcome:welcome }
```

I installed the bundle (~2.3) with composer . 

**Any ideas where my error could be?**
