### ISSUE TITLE
Getting route name

### ISSUE THREAD

**Issue by EmmanuelVella** [BeSimple/BeSimpleI18nRoutingBundle#7]
Hi,

I have a route configured in English and French :

```
house_list:
    locales:
        fr: /fr/maison/
        en: /en/house/
```

When I do a `app/console router:debug`, I have these 2 routes :

```
house_list.fr
house_list.en
```

The problem is that when I do this :
`$this->getRequest()->attributes->get('_route');`

It returns `house_list` instead of - for example - `house_list.fr`

Is it a bug ?
