### ISSUE TITLE
Use Symfony Container Parameter as route locale

### ISSUE THREAD

**Issue by alexander-schranz** [BeSimple/BeSimpleI18nRoutingBundle#72]
I can't use a parameter for locales?

``` yml
my_i18n_route:
    locales: %my_parameter%
    defaults: { _controller: "my_controller:indexAction" }
```

``` bash
Catchable Fatal Error: Argument 2 passed to 
BeSimple\I18nRoutingBundle\Routing\I18nRouteCollectionBuilder::buildCollection()
must be of the type array, string given
```

**Comment by Chrisp1tv** [comment]
I don't know if it will work, but try it :

```yaml
my_i18n_route:
    locales: [ %my_parameter% ]
    defaults: { _controller: "my_controller:indexAction" }
```

This error occured because you passed only your parameter instead of an array, as needed.
