### ISSUE TITLE
Url without locale and default locale

### ISSUE THREAD

**Issue by Mattabile** [BeSimple/BeSimpleI18nRoutingBundle#76]
Hi,

I'm not sure if this is a issue ! 
This is my i18n.yml  : 
```
accueil:
    locales:  { en: "/en", fr: "/", es: "/es" }
    defaults: { _controller: MySiteWebBundle:Default:index }
```
Note that french language locale path  is  "/"
This is my app/routing.yml : 
```
i18nroute:
    resource: "@ MySiteWebBundle/Resources/config/i18n.yml"
    type: be_simple_i18n
    prefix:   /
```
Note that i not use locale in prefix

my url www.mySIte.com shows  the page "Welcome to Symfony"
i can't get my french version Homepage. Why ?
Without use of BeSimpleI18nRoutingBundle  www.mySIte.com request redirect to www.mySIte.com/fr automatically. With BeSimple Bundle the Request www.mySite.com is intercepted by default Controller of Symfony2 framework, i don't know where is this default controller,I dare not modify the Framework.
Where is my issue ?
