### ISSUE TITLE
Exception on duplicated translation

### ISSUE THREAD

**Issue by aistis-** [BeSimple/BeSimpleI18nRoutingBundle#91]
If I have a route defined:

```
my_blog_index:
    locales:
        en: '/news-blog'
        de: '/news-blog'
    defaults:
        _controller: 'MyBlogBundle:Blog:index'
```

I got an exception:

```
An exception has been thrown during the rendering of a template ("I18nRoute "my_blog_index.en" (de) does not exist.") in :Website/Layout:_random_twig_template.html.twig at line 6.
```

It works fine if I change route pattern in de:

```
my_blog_index:
    locales:
        en: '/news-blog'
        de: '/news-blog-2'
    defaults:
        _controller: 'MyBlogBundle:Blog:index'
```

**Comment by boekkooi** [comment]
Hi @aistis- 

This is expected behavior since both paths are the same it is impossible for the router to know what locale is intended or are you using a prefix which loads the yaml? 

Possible fix you be to use:
```YAML
my_blog_index:
    locales:
        en: '/news-blog'
        de: '/nachrichten-blog'
    defaults:
        _controller: 'MyBlogBundle:Blog:index'
```
