### ISSUE TITLE
Locale in path

### ISSUE THREAD

**Issue by aistis-** [BeSimple/BeSimpleI18nRoutingBundle#92]
Hello,

I have a case where the paths of the site looks:

- example.com/en/banana
- example.com/fr/banane
- example.com/lt/bananas

My current routing definition:

```
# app/config/routing.yml
my_fruits:
    resource: '@MyFruitsBundle/Resources/config/routing/banana.yml'
    type: be_simple_i18n
    prefix:   /{_locale}/
    requirements:
        _locale: 'en|fr|de'
```

```
# src/My/FruitsBundle/Resources/config/routing/banana.yml
my_fruits_banana:
    locales:
        en: '/banana'
        fr: '/banane'
        de: '/bananas'
    defaults:
        _controller: 'MyFruitsBundle:Banana:list'
```
How would be possible to deny paths with mismatched `_locale` and parameter with a translation locale?

What I want to achieve:

- example.com/en/banana - **200**
- example.com/fr/banane - **200**
- example.com/lt/bananas - **200**
- example.com/fr/banana - **404**
- example.com/lt/banane - **404**
- example.com/en/bananas - **404**

**Comment by aistis-** [comment]
Hmmmm, looks like it does the trick:

```
    prefix:
        en: '/{_locale}'
        de: '/{_locale}'
    requirements:
        _locale: '%requiredlocales%'
```

**Comment by aistis-** [comment]
Actually this configuration works! **BUT** it does not work, if between `app/config/routing.yml` and `src/My/FruitsBundle/Resources/config/routing/banana.yml` exist middleware routing file with no prefix defined. I18nGenerator is not able to generate prefixed paths anymore.

**Comment by f34nc015** [comment]
Hey @aistis- 
I try to achieve exaclty that. I can't make it work though. 
Are you saying it works? I tried to add a prefix in app/config/routing.yml, but example.com/fr/banana still send back a 200.

**Comment by frankdejonge** [comment]
@aistis- you can import a route file with a prefix like:

```yaml
my_fruits:
    resource: '@MyFruitsBundle/Resources/config/routing/banana.yml'
    type: be_simple_i18n
    prefix:
        en: en
        fr: fr
```

This is not only strict, it's also WAY more performant in terms of route matching. Because the dumped Symfony routes does static prefix optimisations in order to prevent regex matches, with the way you do it _every_ route check is a regex.

Note that the route definition itself needs to be imported as `type: be_simple_i18n`.
