### ISSUE TITLE
be_simple_i18n_routing

### ISSUE THREAD

**Issue by radospanny** [BeSimple/BeSimpleI18nRoutingBundle#97]
I set configuration in config.yml as described in README file.

```
be_simple_i18n_routing:
    locales:
        supported: ['en', 'es']
        filter: true
        strict: true
```

But there is thrown an exception "_Unrecognized option "locales" under "be_simple_i18n_routing"_" in application.
